"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_PRESS_BEHAVIOR = exports.DEFAULT_OPACITY = exports.DEFAULT_ENABLE_TOUCH_THROUGH = exports.DEFAULT_DISAPPEARS_ON_INDEX = exports.DEFAULT_APPEARS_ON_INDEX = exports.DEFAULT_ACCESSIBLE = exports.DEFAULT_ACCESSIBILITY_ROLE = exports.DEFAULT_ACCESSIBILITY_LABEL = exports.DEFAULT_ACCESSIBILITY_HINT = void 0;
const DEFAULT_OPACITY = exports.DEFAULT_OPACITY = 0.5;
const DEFAULT_APPEARS_ON_INDEX = exports.DEFAULT_APPEARS_ON_INDEX = 1;
const DEFAULT_DISAPPEARS_ON_INDEX = exports.DEFAULT_DISAPPEARS_ON_INDEX = 0;
const DEFAULT_ENABLE_TOUCH_THROUGH = exports.DEFAULT_ENABLE_TOUCH_THROUGH = false;
const DEFAULT_PRESS_BEHAVIOR = exports.DEFAULT_PRESS_BEHAVIOR = 'close';
const DEFAULT_ACCESSIBLE = exports.DEFAULT_ACCESSIBLE = false;
const DEFAULT_ACCESSIBILITY_ROLE = exports.DEFAULT_ACCESSIBILITY_ROLE = undefined;
const DEFAULT_ACCESSIBILITY_LABEL = exports.DEFAULT_ACCESSIBILITY_LABEL = undefined;
const DEFAULT_ACCESSIBILITY_HINT = exports.DEFAULT_ACCESSIBILITY_HINT = undefined;
//# sourceMappingURL=constants.js.map