"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_PRESS_BEHAVIOR = exports.DEFAULT_ENABLE_TOUCH_THROUGH = exports.DEFAULT_DISAPPEARS_ON_INDEX = exports.DEFAULT_APPEARS_ON_INDEX = exports.DEFAULT_OPACITY = void 0;
const DEFAULT_OPACITY = 0.5;
exports.DEFAULT_OPACITY = DEFAULT_OPACITY;
const DEFAULT_APPEARS_ON_INDEX = 1;
exports.DEFAULT_APPEARS_ON_INDEX = DEFAULT_APPEARS_ON_INDEX;
const DEFAULT_DISAPPEARS_ON_INDEX = 0;
exports.DEFAULT_DISAPPEARS_ON_INDEX = DEFAULT_DISAPPEARS_ON_INDEX;
const DEFAULT_ENABLE_TOUCH_THROUGH = false;
exports.DEFAULT_ENABLE_TOUCH_THROUGH = DEFAULT_ENABLE_TOUCH_THROUGH;
const DEFAULT_PRESS_BEHAVIOR = 'close';
exports.DEFAULT_PRESS_BEHAVIOR = DEFAULT_PRESS_BEHAVIOR;
//# sourceMappingURL=constants.js.map