const DEFAULT_STACK_BEHAVIOR = 'switch';
const DEFAULT_ENABLE_DISMISS_ON_CLOSE = true;

enum MODAL_STATUS {
  INITIAL,
  PRESENTED,
  CLOSED,
  MINIMIZED,
  MINIMIZING,
  ANIMATING,
  DISMISSING,
  DISMISSED,
}

export {
  DEFAULT_ENABLE_DISMISS_ON_CLOSE,
  DEFAULT_STACK_BEHAVIOR,
  MODAL_STATUS,
};
