"use strict";

const DEFAULT_ACCESSIBLE = false;
const DEFAULT_ACCESSIBILITY_ROLE = undefined;
const DEFAULT_ACCESSIBILITY_LABEL = undefined;
const DEFAULT_ACCESSIBILITY_HINT = undefined;
export { DEFAULT_ACCESSIBLE, DEFAULT_ACCESSIBILITY_ROLE, DEFAULT_ACCESSIBILITY_LABEL, DEFAULT_ACCESSIBILITY_HINT };
//# sourceMappingURL=constants.js.map