import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // "bottom-sheet": [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  'bottom-sheet': [
    {
      type: 'category',
      label: 'Bottom Sheet',
      link: {
        type: 'doc',
        id: 'index',
      },
      items: [
        'usage',
        'props',
        'methods',
        'hooks',
        'scrollables',
        {
          type: 'category',
          label: 'Components',
          items: [
            'components/bottomsheetview',
            'components/bottomsheetscrollview',
            'components/bottomsheetflatlist',
            'components/bottomsheetflashlist',
            'components/bottomsheetsectionlist',
            'components/bottomsheetvirtualizedlist',
            'components/bottomsheetbackdrop',
            'components/bottomsheetfooter',
            'components/bottomsheettextinput',
          ],
        },
      ],
    },
    {
      type: 'html',
      value: "<hr class='margin-vert--md margin-horiz--md' />",
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Bottom Sheet Modal',
      link: {
        type: 'doc',
        id: 'modal/index',
      },
      items: ['modal/usage', 'modal/props', 'modal/methods', 'modal/hooks'],
    },
    {
      type: 'html',
      value: "<hr class='margin-vert--md margin-horiz--md' />",
      defaultStyle: false,
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/web-support',
        'guides/dynamic-sizing',
        'guides/custom-handle',
        'guides/custom-backdrop',
        'guides/custom-background',
        'guides/custom-footer',
        'guides/detach-modal',
        'guides/keyboard-handling',
        'guides/pull-to-refresh',
        'guides/adding-shadow',
        'guides/react-navigation-integration',
      ],
    },
    'troubleshooting',
    'faq',
  ],
};

export default sidebars;
